version: '3.8'

services:
  # FastAPI Backend Service
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - XAI_API_KEY=${XAI_API_KEY}
      - XAI_MODEL=${XAI_MODEL:-grok-3-mini}
      - OLLAMA_EMBEDDING_MODEL=${OLLAMA_EMBEDDING_MODEL:-nomic-embed-text}
      - CHROMADB_LOCAL_DIR=/app/chromadb
    volumes:
      - ./chromadb:/app/chromadb
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Streamlit Frontend Service
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - HOST=fastapi
      - FASTAPI_PORT=8000
      - STREAMLIT_BROWSER_GATHERUSAGESTATS=false
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
    depends_on:
      fastapi:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: rag-network
